### PR TITLE
Fix build on macOS

### PR DESCRIPTION
**Pull request by smarsching**
There were a couple of problems when building on macOS (12.6), as described in #281. This MR fixes these problems.

### CODE REVIEW

**Comment by phako** [comment]
Is that with target Apple silicon or x86 (mostly talking about the size_t stuff there)

**Comment by smarsching** [comment]
It is on x86_64. I currently do not have access to an ARM-based system to test it there.

**Review by mhier — APPROVED** [review]

**Comment by mhier** [comment]
@killenb Can we merge this already or would it disturb the focus work?

**Comment by mhier** [comment]
> Is that with target Apple silicon or x86 (mostly talking about the size_t stuff there)

I guess this is a weird C++ thing: "unsigned long long int" is not the same type as "unsigned long int" despite both being unsigned 64 bit integers and hence having the same value range and bit representation. uint64_t probably can be typedef'd either way, depending on the system headers.

**Review by killenb — APPROVED** [review]
The changes should not affect any work in the focus. I don't expect any merge conflicts.

**Pull request merged**
