### PR TITLE
added dlmopen as first choice to load the plugin.

### PR DESCRIPTION
**Pull request by nshehz**
Please review. If approve, please merge the branch and close the ticket.

### CODE REVIEW

**Comment by mhier** [comment]
testRunTimeBackendLoading crashes in a very strange way for me, I don't really understand what's going wrong there.

**Comment by mhier** [comment]
Unrelated to my previous comment: instead of the assert(backend_name != nullptr) you should throw a proper exception when not all required symbols are found.

**Comment by nshehz** [comment]
The best I can see at the moment with gdb that it crashes as it tries to release memory in malloc.c 
if (chunk_is_mmapped (p))                       /* release mmapped memory. */
{
/* See if the dynamic brk/mmap threshold needs adjusting.
Dumped fake mmapped chunks do not affect the threshold.  */
if (!mp_.no_dyn_threshold
&& chunksize_nomask (p) > mp_.mmap_threshold
&& chunksize_nomask (p) <= DEFAULT_MMAP_THRESHOLD_MAX
&& !DUMPED_MAIN_ARENA_CHUNK (p))
{
......

**Comment by mhier** [comment]
It was decided not to merge, since the solution with dlmopen does not work

**Pull request closed without merging**
